//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoApp.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PushNotificationSetting
    {
        public long Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateByUserId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public Nullable<int> LastUpdateByUserId { get; set; }
        public int UserId { get; set; }
        public bool WebNotification { get; set; }
        public bool CommentsAttachedToMe { get; set; }
        public bool TasksAssignedToMe { get; set; }
        public bool TasksCompleted { get; set; }
        public bool TasksUncompleted { get; set; }
        public bool CollaboratorJoinedProject { get; set; }
        public bool CollaboratorDeclinedInvitationToProject { get; set; }
        public bool CollaboratorLeftProject { get; set; }
        public bool CollaboratorRemovedFromProject { get; set; }
    }
}
