//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoApp.Business.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ToDoAppStoreEntities : DbContext
    {
        public ToDoAppStoreEntities()
            : base("name=ToDoAppStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<ApplicationRole> ApplicationRoles { get; set; }
        public virtual DbSet<ApplicationUserClaim> ApplicationUserClaims { get; set; }
        public virtual DbSet<ApplicationUserLogin> ApplicationUserLogins { get; set; }
        public virtual DbSet<ApplicationUser> ApplicationUsers { get; set; }
        public virtual DbSet<Audit> Audits { get; set; }
        public virtual DbSet<EmailNotificationSetting> EmailNotificationSettings { get; set; }
        public virtual DbSet<MediaFile> MediaFiles { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Preference> Preferences { get; set; }
        public virtual DbSet<PushNotificationSetting> PushNotificationSettings { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<TaskCategory> TaskCategories { get; set; }
        public virtual DbSet<UserTaskCollaborator> UserTaskCollaborators { get; set; }
        public virtual DbSet<UserTaskComment> UserTaskComments { get; set; }
        public virtual DbSet<UserTaskInTag> UserTaskInTags { get; set; }
        public virtual DbSet<UserTask> UserTasks { get; set; }
    }
}
