//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoApp.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTask
    {
        public long Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateByUserId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public Nullable<int> LastUpdateByUserId { get; set; }
        public string Title { get; set; }
        public int TitleHashCode { get; set; }
        public System.DateTime StartDate { get; set; }
        public int TaskEnumStatusId { get; set; }
        public int OrderId { get; set; }
        public int PriorityEnumId { get; set; }
        public Nullable<long> TaskCategoryId { get; set; }
        public Nullable<long> MediaFileId { get; set; }
        public bool IsArchived { get; set; }
        public string AssignedTo { get; set; }
    }
}
